name: Build and Release

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]  # Modify as per your requirement

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Copy files to dist directory
        run: cp -R src dist

      - name: Build draft version and compile with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile --hidden-import pkg_resources.py2_warn --name my_app main.py

      - name: Create draft release
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          TAG=v${{ github.run_number }}
          TITLE="Release ${{ github.run_number }}"
          BODY=""
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{\"tag_name\":\"$TAG\",\"name\":\"$TITLE\",\"body\":\"$BODY\",\"draft\":true}"

      - name: Get release ID
        id: get_release_id
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          TAG=v${{ github.run_number }}
          RELEASE_ID=$(curl -s \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG | jq -r '.id')
          echo "::set-output name=release_id::$RELEASE_ID"

      - name: Upload executable as release asset
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          RELEASE_ID=${{ steps.get_release_id.outputs.release_id }}
          FILE_PATH="dist/my_app"
          FILE_NAME="my_app"
          UPLOAD_URL=$(curl -s \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=$FILE_NAME | jq -r '.upload_url')
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @$FILE_PATH \
            "$UPLOAD_URL?name=$FILE_NAME"
