name: Compile Python Code

on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile Python code
        run: |
          pyinstaller --onefile main.py

          # Iterate over all .py files in the 'src' directory and compile them
          python -c "import glob, os; [os.system(f'pyinstaller --onefile {filename}') for filename in glob.glob('src/*.py')]"

          # Move the executables to a separate directory
          mkdir -p dist
          mv dist/*.exe dist/windows/ || true
          mv dist/*.out dist/linux/ || true
          mv dist/*.app dist/macos/ || true

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/windows/*
            dist/linux/*
            dist/macos/*
          draft: true
          title: Draft Release