name: Compile Python Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile Python code
        run: |
          pyinstaller --onefile main.py

          # Iterate over all .py files in the 'src' directory and compile them
          for file in src/*.py; do
            pyinstaller --onefile "$file"
          done

          # Move the executables to a separate directory
          mkdir -p dist
          mv dist/*.exe dist/windows/
          mv dist/*.out dist/linux/
          mv dist/*.app dist/macos/

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/windows/*
            dist/linux/*
            dist/macos/*
          draft: true
          title: Draft Release

